version: "3.9"

services:
  app:
    build:
      context: .
      # powyżej root directory, dlatego kropka (current dir)
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    # jeżeli nie określimy komendy - zostanie wykorzystana ta powyżej